version: '3'

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "2020:2020" 
    environment:
      db_name: ${db_name}
      db_user: ${db_user}
      db_password: ${db_password}
      db_host: ${db_host}
      db_port: ${db_port}
    volumes:
     - ./src:/app
      - /app/node_modules
    networks:
      - coolify

networks:
  coolify:
    external: true

volumes:
  postgres_data:
  
