version: '3'

services:
  postgres:
    image: postgres:14
    ports:
      - "5435:5435"
    environment:
      POSTGRES_PASSWORD: ${db_password}
      POSTGRES_DB: ${db_name}
      POSTGRES_USER: ${db_user}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "2020:2020" 
    depends_on:
      - postgres
    environment:
      db_name: ${db_name}
      db_user: ${db_user}
      db_password: ${db_password}
      db_host: ${db_host}
      db_port: ${db_port}
    volumes:
      - /app/node_modules

volumes:
  postgres_data:
  
